name: Build and Deploy to OpenShift

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      #- name: Set up Maven
      #  uses: actions/setup-maven-action@v3
      #  with:
       #   distribution: 'maven'
       #   maven-version: '3.8.4'
     #     java-version: '17'

      - name: Build with Maven
        run: mvn clean package -Dmaven.test.skip=true

      - name: Set up OpenShift CLI
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server: https://api.rm2.thpm.p1.openshiftapps.com:6443
          token: sha256~gyKB_jOtMxtuO8CnoI7g6FTgEQmD96kMufR_5qEjfPE

      - name: Deploy to OpenShift
        run:
          oc project banking-portal-api
          oc new-app --name=banking-portal-api --image-stream=java:17 --binary=true
          oc start-build banking-portal-api --from-file=target/banking-portal-api-0.0.1-SNAPSHOT.jar --follow
          oc expose svc/banking-portal-api
